apiVersion: v1
kind: Service
metadata:
  name: eventsec-backend
spec:
  selector:
    app: eventsec-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventsec-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventsec-backend
  template:
    metadata:
      labels:
        app: eventsec-backend
    spec:
      containers:
        - name: backend
          image: eventsec_enterprise_fixed-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: postgresql+psycopg2://eventsec:eventsec@eventsec-postgres:5432/eventsec
            - name: OPENSEARCH_URL
              value: http://eventsec-opensearch:9200
            - name: SECRET_KEY_FILE
              value: /var/run/secrets/eventsec/jwt
            - name: AGENT_ENROLLMENT_KEY_FILE
              value: /var/run/secrets/eventsec/enrollment
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: tls-certs
              mountPath: /certs
              readOnly: true
            - name: eventsec-secret-vol
              mountPath: /var/run/secrets/eventsec
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: eventsec-tls
            optional: true
        - name: eventsec-secret-vol
          secret:
            secretName: eventsec-secrets

