apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eventsec
resources:
  - namespace.yaml
  - postgres.yaml
  - opensearch.yaml
  - backend.yaml
  - frontend.yaml
  - secrets-example.yaml

