apiVersion: v1
kind: Service
metadata:
  name: eventsec-opensearch
spec:
  selector:
    app: eventsec-opensearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventsec-opensearch
spec:
  serviceName: eventsec-opensearch
  replicas: 1
  selector:
    matchLabels:
      app: eventsec-opensearch
  template:
    metadata:
      labels:
        app: eventsec-opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.12.0
          env:
            - name: discovery.type
              value: single-node
            - name: plugins.security.disabled
              value: "true"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: eventsec-os-data
              mountPath: /usr/share/opensearch/data
  volumeClaimTemplates:
    - metadata:
        name: eventsec-os-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi

